# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
warnings_are_errors: true

repos:
  CRAN: https://cran.rstudio.com
  GRAN: https://owi.usgs.gov/R

before_script:
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('rmarkdown')"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(); covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
